version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restar: always
    ports:
      -"${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex 
  db:
    image: mongo:5
    container_name: mongo_poke
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE: nest-pokemon
    #volumes:
    #  - ./mongo:/data/db